def takvimmenu():
    print("╔═══════════════════╗")
    print("║TAKVİM             ║")
    print("║1-Ocak             ║")
    print("║2-Şubat            ║")
    print("║3-Mart             ║")
    print("║4-Nisan            ║")
    print("║5-Mayıs            ║")
    print("║6-Haziran          ║")
    print("║7-Temmuz           ║")
    print("║8-Ağustos          ║")
    print("║9-Eylül            ║")
    print("║10-Ekim            ║")
    print("║11-Kasım           ║")
    print("║12-Aralık          ║")
    print("║13-Çıkış (e)       ║")
    print("║  seçiminiz nedir? ║")
    print("╚═══════════════════╝")
